[theme]
primaryColor = "#D89414"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#EAF0F6"
textColor = "#10243E"
font = "sans serif"

[server]
headless = true
maxUploadSize = 10
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
